spring:
  application:
    name: price-fetcher-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${PRICE_FETCHER_DB_NAME}
    username: ${PRICE_FETCHER_DB_USER}
    password: ${PRICE_FETCHER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: ${PRICE_FETCHER_SENDGRID_API_KEY}
server:
  port: 8501

amazon-config:
  session-id: ${AMAZON_SESSION_ID}

sendgrid-config:
  from: ${SENDGRID_FROM}